// language-service.js — RapydScript Monaco Language Service
// Auto-generated by tools/build-language-service.js — do not edit directly.
// Source: src/monaco-language-service/
// Usage:  import { registerRapydScript } from './language-service.js';


// ── scope.js ────────────────────────────────────────────────────────────

// scope.js — ScopeMap data structures for the RapydScript language service.
//
// Position convention throughout this file:
//   line   — 1-indexed  (matches Monaco's lineNumber)
//   column — 1-indexed  (matches Monaco's column)
// AST tokens use 1-indexed lines and 0-indexed cols; the analyzer converts
// before storing so callers always work with fully 1-indexed numbers.

// ---------------------------------------------------------------------------
// SymbolInfo
// ---------------------------------------------------------------------------

class SymbolInfo {
    /**
     * @param {object} opts
     * @param {string}  opts.name
     * @param {string}  opts.kind  'function'|'method'|'class'|'variable'|'parameter'|'import'
     * @param {{line:number,column:number}} opts.defined_at  1-indexed line and column
     * @param {number}  opts.scope_depth
     * @param {string|null} [opts.doc]
     * @param {Array|null}  [opts.params]  [{name, is_rest, is_kwargs}] for functions/methods
     */
    constructor(opts) {
        this.name        = opts.name;
        this.kind        = opts.kind;
        this.defined_at  = opts.defined_at;   // {line, column} both 1-indexed
        this.scope_depth = opts.scope_depth;
        this.doc            = opts.doc   || null;
        this.params         = opts.params || null;
        this.inferred_class = opts.inferred_class || null;  // 'ClassName' when x = ClassName(...)
        this.type           = null;              // Phase 6: TypeInfo
    }
}

// ---------------------------------------------------------------------------
// ScopeFrame
// ---------------------------------------------------------------------------

class ScopeFrame {
    /**
     * @param {object} opts
     * @param {string}  opts.kind  'module'|'function'|'class'|'comprehension'|'block'
     * @param {string|null} opts.name
     * @param {{start:{line,column}, end:{line,column}}} opts.range  1-indexed
     * @param {ScopeFrame|null} opts.parent
     * @param {number} opts.depth
     */
    constructor(opts) {
        this.kind    = opts.kind;
        this.name    = opts.name || null;
        this.range   = opts.range;
        this.parent  = opts.parent || null;
        this.depth   = opts.depth;
        this.symbols = new Map();  // name → SymbolInfo
    }

    /** Add or overwrite a symbol in this frame. */
    addSymbol(sym) {
        this.symbols.set(sym.name, sym);
    }

    /** Return a symbol by exact name, or null. */
    getSymbol(name) {
        return this.symbols.get(name) || null;
    }
}

// ---------------------------------------------------------------------------
// Range helpers (all positions 1-indexed)
// ---------------------------------------------------------------------------

function range_contains(range, line, column) {
    const { start, end } = range;
    const after_start = (line > start.line) || (line === start.line && column >= start.column);
    const before_end  = (line < end.line)   || (line === end.line   && column <= end.column);
    return after_start && before_end;
}

// ---------------------------------------------------------------------------
// ScopeMap
// ---------------------------------------------------------------------------

class ScopeMap {
    constructor() {
        /** All frames in document order (outer to inner). @type {ScopeFrame[]} */
        this.frames = [];
    }

    /** @internal Called by ScopeBuilder as frames are created. */
    addFrame(frame) {
        this.frames.push(frame);
    }

    /**
     * Return all ScopeFrames whose range contains (line, column), innermost first.
     * Both line and column are 1-indexed (Monaco format).
     * @param {number} line
     * @param {number} column
     * @returns {ScopeFrame[]}
     */
    getScopesAtPosition(line, column) {
        return this.frames
            .filter(f => range_contains(f.range, line, column))
            .sort((a, b) => b.depth - a.depth);
    }

    /**
     * Return every symbol visible at (line, column).
     * When two scopes define the same name, the innermost one wins.
     * Both line and column are 1-indexed (Monaco format).
     * @param {number} line
     * @param {number} column
     * @returns {SymbolInfo[]}
     */
    getSymbolsAtPosition(line, column) {
        const scopes = this.getScopesAtPosition(line, column);
        const seen   = new Set();
        const result = [];
        for (const scope of scopes) {
            for (const [name, sym] of scope.symbols) {
                if (!seen.has(name)) {
                    seen.add(name);
                    result.push(sym);
                }
            }
        }
        return result;
    }

    /**
     * Look up a single symbol by name that is visible at (line, column).
     * Returns the innermost definition, or null if not found.
     * Both line and column are 1-indexed (Monaco format).
     * @param {string} name
     * @param {number} line
     * @param {number} column
     * @returns {SymbolInfo|null}
     */
    getSymbol(name, line, column) {
        const scopes = this.getScopesAtPosition(line, column);
        for (const scope of scopes) {
            const sym = scope.getSymbol(name);
            if (sym) return sym;
        }
        return null;
    }

    /**
     * Return all symbols across every scope in the document.
     * @returns {SymbolInfo[]}
     */
    getAllSymbols() {
        const result = [];
        for (const frame of this.frames) {
            for (const sym of frame.symbols.values()) {
                result.push(sym);
            }
        }
        return result;
    }
}


// ── diagnostics.js ──────────────────────────────────────────────────────

// diagnostics.js — RapydScript linter for Monaco
// Ported from tools/lint.js; browser-compatible ES module (no Node.js deps).
// Usage:
//   const d = new Diagnostics(compiler, extraBuiltins);
//   const markers = d.check(sourceCode);  // returns Monaco IMarkerData[]

const WARN = 1, ERROR = 2;

const MESSAGES = {
    'undef':          'Undefined symbol: "{name}"',
    'unused-import':  '"{name}" is imported but not used',
    'unused-local':   '"{name}" is defined but not used',
    'loop-shadowed':  'The loop variable "{name}" was previously used in this scope at line: {line}',
    'extra-semicolon':'This semi-colon is not needed',
    'eol-semicolon':  'Semi-colons at the end of the line are unnecessary',
    'func-in-branch': 'Named functions/classes inside a branch are not allowed in strict mode',
    'syntax-err':     'Syntax error: {name}',
    'import-err':     'Import error: {name}',
    'def-after-use':  'The symbol "{name}" is defined (at line {line}) after it is used',
    'dup-key':        'Duplicate key "{name}" in object literal',
    'dup-method':     'The method "{name}" was defined previously at line: {line}',
};

// Symbols always available in RapydScript (from tools/lint.js BUILTINS list).
export const BASE_BUILTINS = (
    'this self window document chr ord iterator_symbol print len range dir' +
    ' eval undefined arguments abs max min enumerate pow callable reversed sum' +
    ' getattr isFinite setattr hasattr parseInt parseFloat options_object' +
    ' isNaN JSON Math list set list_wrap ρσ_modules require bool int bin' +
    ' float iter Error EvalError set_wrap RangeError ReferenceError SyntaxError' +
    ' str TypeError URIError Exception AssertionError IndexError AttributeError KeyError' +
    ' ValueError ZeroDivisionError map hex filter zip dict dict_wrap UnicodeDecodeError HTMLCollection' +
    ' NodeList alert console Node Symbol NamedNodeMap ρσ_eslice ρσ_delslice Number' +
    ' Boolean encodeURIComponent decodeURIComponent setTimeout setInterval' +
    ' setImmediate clearTimeout clearInterval clearImmediate requestAnimationFrame' +
    ' id repr sorted __name__ equals get_module ρσ_str jstype divmod NaN'
).split(' ');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function has_prop(obj, name) {
    return Object.prototype.hasOwnProperty.call(obj, name);
}

function msg_from_node(ident, name, node, level, line) {
    name = name || (node.name ? (node.name.name || node.name) : '');
    const msg = MESSAGES[ident]
        .replace('{name}', name || '')
        .replace('{line}', line !== undefined ? line : '');
    return {
        start_line: node.start ? node.start.line : undefined,
        start_col:  node.start ? node.start.col  : undefined,
        end_line:   node.end   ? node.end.line   : undefined,
        end_col:    node.end   ? node.end.col    : undefined,
        ident,
        message: msg,
        level: level || ERROR,
        name,
        other_line: line,
    };
}

// ---------------------------------------------------------------------------
// Binding
// ---------------------------------------------------------------------------

function Binding(name, node, options) {
    options = options || {};
    this.node          = node;
    this.name          = name;
    this.is_import     = !!options.is_import;
    this.is_function   = !!options.is_function;
    this.is_func_arg   = !!options.is_func_arg;
    this.is_method     = !!options.is_method;
    this.is_loop       = false;
    this.used          = false;
}

// ---------------------------------------------------------------------------
// Scope
// ---------------------------------------------------------------------------

function Scope(is_toplevel, parent_scope, is_class) {
    this.parent_scope          = parent_scope;
    this.is_toplevel           = !!is_toplevel;
    this.is_class              = !!is_class;
    this.bindings              = Object.create(null);
    this.children              = [];
    this.shadowed              = [];
    this.undefined_references  = Object.create(null);
    this.unused_bindings       = Object.create(null);
    this.nonlocals             = Object.create(null);
    this.defined_after_use     = Object.create(null);
    this.seen_method_names     = Object.create(null);
    this.methods               = Object.create(null);
}

Scope.prototype.add_binding = function(name, node, options) {
    const already_bound = has_prop(this.bindings, name);
    const b = new Binding(name, node, options);
    if (already_bound) {
        if (this.bindings[name].used) b.used = true;
        this.shadowed.push([name, this.bindings[name], b]);
    }
    this.bindings[name] = b;
    return b;
};

Scope.prototype.add_nonlocal = function(name) {
    this.nonlocals[name] = true;
};

Scope.prototype.register_use = function(name, node) {
    if (has_prop(this.bindings, name)) {
        this.bindings[name].used = true;
    } else {
        this.undefined_references[name] = node;
    }
};

Scope.prototype.for_descendants = function(func) {
    this.children.forEach(child => { func(child); child.for_descendants(func); });
};

Scope.prototype.finalize = function() {
    // Detect defined-after-use
    Object.keys(this.undefined_references).forEach(name => {
        if (has_prop(this.bindings, name) && !has_prop(this.nonlocals, name)) {
            const b = this.bindings[name];
            b.used = true;
            if (!has_prop(this.defined_after_use, name))
                this.defined_after_use[name] = [this.undefined_references[name], b];
            delete this.undefined_references[name];
        }
        if (has_prop(this.methods, name)) delete this.undefined_references[name];
    });

    // Detect unused bindings
    Object.keys(this.bindings).forEach(name => {
        const b = this.bindings[name];
        let found = false;
        this.for_descendants(scope => {
            if (has_prop(scope.undefined_references, name)) {
                found = true;
                delete scope.undefined_references[name];
            } else if (has_prop(scope.nonlocals, name) && has_prop(scope.bindings, name)) {
                found = true;
            }
        });
        if (!found && !b.used && !b.is_loop)
            this.unused_bindings[name] = b;
    });
};

Scope.prototype.messages = function() {
    const ans = [];

    Object.keys(this.undefined_references).forEach(name => {
        if (!(this.is_toplevel && has_prop(this.nonlocals, name))) {
            const node = this.undefined_references[name];
            ans.push(msg_from_node('undef', name, node));
        }
    });

    Object.keys(this.unused_bindings).forEach(name => {
        const b = this.unused_bindings[name];
        if (b.is_import) {
            ans.push(msg_from_node('unused-import', name, b.node));
        } else if (!this.is_toplevel && !this.is_class && !b.is_func_arg && !b.is_method && !has_prop(this.nonlocals, name)) {
            ans.push(msg_from_node('unused-local', name, b.node));
        }
    });

    this.shadowed.forEach(([name, first, second]) => {
        if (second.is_loop && !first.is_loop) {
            const line = first.node.start ? first.node.start.line : undefined;
            ans.push(msg_from_node('loop-shadowed', name, second.node, ERROR, line));
        }
    });

    Object.keys(this.defined_after_use).forEach(name => {
        const [use, binding] = this.defined_after_use[name];
        ans.push(msg_from_node('def-after-use', name, use, ERROR, binding.node.start.line));
    });

    return ans;
};

// ---------------------------------------------------------------------------
// Linter — mirrors the Linter in tools/lint.js
// ---------------------------------------------------------------------------

function Linter(RS, toplevel, code, builtins) {
    this.RS             = RS;
    this.scopes         = [];
    this.walked_scopes  = [];
    this.current_node   = null;
    this.branches       = [];
    this.messages       = [];
    this.builtins       = builtins;

    this.add_binding = function(name, binding_node) {
        const scope = this.scopes[this.scopes.length - 1];
        const node  = this.current_node;
        const opts  = {
            is_import:   (node instanceof RS.AST_Import || node instanceof RS.AST_ImportedVar),
            is_function: (node instanceof RS.AST_Lambda),
            is_method:   (node instanceof RS.AST_Method),
            is_func_arg: (node instanceof RS.AST_SymbolFunarg),
        };
        return scope.add_binding(name, binding_node || node, opts);
    };

    this.add_nonlocal = function(name) {
        this.scopes[this.scopes.length - 1].add_nonlocal(name);
    };

    this.register_use = function(name) {
        this.scopes[this.scopes.length - 1].register_use(name, this.current_node);
    };

    this.handle_import = function() {
        const node = this.current_node;
        if (!node.argnames) {
            const name = node.alias ? node.alias.name : node.key.split('.', 1)[0];
            this.add_binding(name, node.alias || node);
        }
    };

    this.handle_imported_var = function() {
        const node = this.current_node;
        const name = node.alias ? node.alias.name : node.name;
        this.add_binding(name);
    };

    this.handle_lambda = function() {
        const node  = this.current_node;
        const name  = node.name ? node.name.name : undefined;
        const scope = this.scopes[this.scopes.length - 1];
        if (this.branches.length && name)
            this.messages.push(msg_from_node('func-in-branch', name, node));
        if (name) {
            if (node instanceof RS.AST_Method) {
                scope.methods[name] = true;
                if (has_prop(scope.seen_method_names, name)) {
                    if (!node.is_setter)
                        this.messages.push(msg_from_node('dup-method', name, node, WARN, scope.seen_method_names[name]));
                } else {
                    scope.seen_method_names[name] = node.start.line;
                }
            } else {
                this.add_binding(name);
            }
        }
    };

    this.handle_assign = function() {
        const node = this.current_node;
        const handle_destructured = (flat) => {
            flat.forEach(cnode => {
                if (cnode instanceof RS.AST_SymbolRef) {
                    this.current_node = cnode;
                    cnode.lint_visited = true;
                    this.add_binding(cnode.name);
                    this.current_node = node;
                }
            });
        };
        if (node.left instanceof RS.AST_SymbolRef) {
            node.left.lint_visited = node.operator === '=';
            if (node.operator === '=') {
                this.current_node = node.left;
                this.add_binding(node.left.name);
                this.current_node = node;
            }
        } else if (node.left instanceof RS.AST_Array) {
            handle_destructured(node.left.flatten());
        } else if (node.left instanceof RS.AST_Seq && node.left.car instanceof RS.AST_SymbolRef) {
            handle_destructured(node.left.to_array());
        }
    };

    this.handle_vardef = function() {
        const node = this.current_node;
        if (node.name instanceof RS.AST_SymbolNonlocal) {
            this.add_nonlocal(node.name.name);
        } else {
            this.add_binding(node.name.name, node.name);
        }
    };

    this.handle_symbol_ref = function() {
        this.register_use(this.current_node.name);
    };

    this.handle_decorator = function() {
        const node = this.current_node.expression;
        if (node instanceof RS.AST_SymbolRef &&
            RS.compile_time_decorators.indexOf(node.name) !== -1)
            node.lint_visited = true;
    };

    this.handle_scope = function() {
        const node   = this.current_node;
        const parent = this.scopes.length ? this.scopes[this.scopes.length - 1] : null;
        const nscope = new Scope(
            node instanceof RS.AST_Toplevel,
            parent,
            node instanceof RS.AST_Class
        );
        if (parent) parent.children.push(nscope);
        this.scopes.push(nscope);
    };

    this.handle_symbol_funarg = function() {
        this.add_binding(this.current_node.name);
    };

    this.handle_comprehension = function() {
        this.handle_scope();
        this.handle_for_in();
    };

    this.handle_for_in = function() {
        const node = this.current_node;
        if (node.init instanceof RS.AST_SymbolRef) {
            this.add_binding(node.init.name).is_loop = true;
            node.init.lint_visited = true;
        } else if (node.init instanceof RS.AST_Array) {
            node.init.elements.forEach(cnode => {
                if (cnode instanceof RS.AST_Seq) cnode = cnode.to_array();
                if (cnode instanceof RS.AST_SymbolRef) cnode = [cnode];
                if (Array.isArray(cnode)) {
                    cnode.forEach(elem => {
                        if (elem instanceof RS.AST_SymbolRef) {
                            this.current_node = elem;
                            elem.lint_visited = true;
                            this.add_binding(elem.name).is_loop = true;
                            this.current_node = node;
                        }
                    });
                }
            });
        }
    };

    this.handle_for_js = function() {
        const js         = this.current_node.condition.value;
        const statements = js.split(';');
        let   decl       = statements[0].trim();
        if (decl.startsWith('var ')) decl = decl.slice(4);
        decl.split(',').forEach(part => {
            const m = /^[a-zA-Z0-9_]+/.exec(part.trimLeft());
            if (m) this.add_binding(m[0]);
        });
    };

    this.handle_except = function() {
        const node = this.current_node;
        if (node.argname) this.add_binding(node.argname.name, node.argname);
    };

    this.handle_empty_statement = function() {
        if (this.current_node.stype === ';')
            this.messages.push(msg_from_node('extra-semicolon', ';', this.current_node, WARN));
    };

    this.handle_class = function() {
        const node = this.current_node;
        if (node.name) {
            node.name.lint_visited = true;
            this.add_binding(node.name.name, node.name);
        }
    };

    this.handle_object_literal = function() {
        const node = this.current_node;
        const seen = Object.create(null);
        (node.properties || []).forEach(prop => {
            if (prop.key instanceof RS.AST_Constant) {
                const val = prop.key.value;
                if (has_prop(seen, val))
                    this.messages.push(msg_from_node('dup-key', val, prop));
                seen[val] = true;
            }
        });
    };

    this.handle_call = function() {
        const node = this.current_node;
        if (node.args.kwargs)
            node.args.kwargs.forEach(kw => { kw[0].lint_visited = true; });
    };

    this.handle_with_clause = function() {
        const node = this.current_node;
        if (node.alias) this.add_binding(node.alias.name);
    };

    // The visitor function called by toplevel.walk()
    this._visit = function(node, cont) {
        if (node.lint_visited) return;
        this.current_node = node;

        const scope_count  = this.scopes.length;
        const branch_count = this.branches.length;

        if (node instanceof RS.AST_If   || node instanceof RS.AST_Try  ||
            node instanceof RS.AST_Catch || node instanceof RS.AST_Except ||
            node instanceof RS.AST_Else) {
            this.branches.push(1);
        }

        if      (node instanceof RS.AST_Lambda)         this.handle_lambda();
        else if (node instanceof RS.AST_Import)          this.handle_import();
        else if (node instanceof RS.AST_ImportedVar)     this.handle_imported_var();
        else if (node instanceof RS.AST_Class)           this.handle_class();
        else if (node instanceof RS.AST_BaseCall)        this.handle_call();
        else if (node instanceof RS.AST_Assign)          this.handle_assign();
        else if (node instanceof RS.AST_VarDef)          this.handle_vardef();
        else if (node instanceof RS.AST_SymbolRef)       this.handle_symbol_ref();
        else if (node instanceof RS.AST_Decorator)       this.handle_decorator();
        else if (node instanceof RS.AST_SymbolFunarg)    this.handle_symbol_funarg();
        else if (node instanceof RS.AST_ListComprehension) this.handle_comprehension();
        else if (node instanceof RS.AST_ForIn)           this.handle_for_in();
        else if (node instanceof RS.AST_ForJS)           this.handle_for_js();
        else if (node instanceof RS.AST_Except)          this.handle_except();
        else if (node instanceof RS.AST_EmptyStatement)  this.handle_empty_statement();
        else if (node instanceof RS.AST_WithClause)      this.handle_with_clause();
        else if (node instanceof RS.AST_Object)          this.handle_object_literal();

        if (node instanceof RS.AST_Scope) this.handle_scope();

        if (cont !== undefined) cont();

        if (this.scopes.length > scope_count) {
            this.scopes[this.scopes.length - 1].finalize();
            this.walked_scopes.push(this.scopes.pop());
        }
        if (this.branches.length > branch_count) this.branches.pop();
    };

    // Collect all messages, apply noqa filters
    this.resolve = function(noqa) {
        noqa = noqa || {};
        let messages = this.messages.slice();

        // eol-semicolon: scan source lines
        code.split('\n').forEach((line, idx) => {
            const trimmed = line.trimRight();
            if (trimmed[trimmed.length - 1] === ';') {
                const ident = 'eol-semicolon';
                messages.push({
                    ident, message: MESSAGES[ident], level: WARN, name: ';',
                    start_line: idx + 1, start_col: trimmed.lastIndexOf(';'),
                });
            }
        });

        // Collect scope messages
        this.walked_scopes.forEach(scope => {
            messages = messages.concat(scope.messages());
        });

        // Filter: builtins, noqa
        messages = messages.filter(msg => {
            if (has_prop(noqa, msg.ident)) return false;
            if (msg.ident === 'undef' && has_prop(this.builtins, msg.name)) return false;
            return true;
        });

        messages.sort((a, b) => {
            const dl = (a.start_line || 0) - (b.start_line || 0);
            return dl !== 0 ? dl : (a.start_col || 0) - (b.start_col || 0);
        });

        return messages;
    };
}

// ---------------------------------------------------------------------------
// Convert lint message → Monaco IMarkerData
// markerSeverity should be { Error, Warning, Info, Hint } numeric values
// ---------------------------------------------------------------------------

function to_marker(msg, markerSeverity) {
    const sline = msg.start_line || 1;
    const scol  = (msg.start_col  !== undefined ? msg.start_col  : 0);
    const eline = msg.end_line   || sline;
    const ecol  = (msg.end_col   !== undefined ? msg.end_col   : scol);

    return {
        severity:        msg.level === WARN ? markerSeverity.Warning : markerSeverity.Error,
        message:         msg.message,
        source:          'rapydscript',
        startLineNumber: sline,
        startColumn:     scol + 1,           // lint uses 0-indexed cols
        endLineNumber:   eline,
        endColumn:       ecol + 2,           // exclusive end, 1-indexed
    };
}

// ---------------------------------------------------------------------------
// Public class
// ---------------------------------------------------------------------------

class Diagnostics {
    /**
     * @param {object} compiler  - window.RapydScript (the compiled compiler)
     * @param {object} [extraBuiltins] - additional symbol names to treat as defined
     */
    constructor(compiler, extraBuiltins) {
        this._RS = compiler;

        // Build the builtins lookup table
        this._builtins = Object.create(null);
        BASE_BUILTINS.forEach(s => { this._builtins[s] = true; });

        // Add NATIVE_CLASSES from the compiler (Array, Promise, Map, etc.)
        if (compiler.NATIVE_CLASSES) {
            Object.keys(compiler.NATIVE_CLASSES).forEach(name => {
                this._builtins[name] = true;
            });
        }

        // Caller-supplied extra builtins (e.g. from d.ts globals)
        if (extraBuiltins) {
            Object.keys(extraBuiltins).forEach(name => {
                this._builtins[name] = true;
            });
        }
    }

    /**
     * Add additional global names (called by DtsRegistry when d.ts files are loaded).
     * @param {string[]} names
     */
    addGlobals(names) {
        names.forEach(n => { this._builtins[n] = true; });
    }

    /**
     * Run the linter on a source string and return Monaco marker objects.
     *
     * @param {string} code - RapydScript source
     * @param {object} [options]
     * @param {object} [options.virtualFiles]  - map of module name → source
     * @param {object} [options.noqa]          - map of ident → true to suppress
     * @param {object} [options.markerSeverity] - monaco.MarkerSeverity enum
     * @returns {Array} Monaco IMarkerData[]
     */
    check(code, options) {
        options = options || {};
        const RS             = this._RS;
        const markerSeverity = options.markerSeverity || { Error: 8, Warning: 4 };
        const noqa           = options.noqa || {};

        let toplevel, messages;

        // --- Parse ---
        try {
            toplevel = RS.parse(code, {
                filename:      'editor.pyj',
                for_linting:   true,
                // virtual files let the parser resolve imports without disk access
                ...(options.virtualFiles ? { virtual_files: options.virtualFiles } : {}),
            });
        } catch (e) {
            if (e instanceof RS.SyntaxError || e instanceof RS.ImportError) {
                const ident = (e instanceof RS.SyntaxError) ? 'syntax-err' : 'import-err';
                const line  = e.line || 1;
                const col   = e.col  || 0;
                return [{
                    severity:        markerSeverity.Error,
                    message:         e.message,
                    source:          'rapydscript',
                    startLineNumber: line,
                    startColumn:     col + 1,
                    endLineNumber:   line,
                    endColumn:       col + 2,
                }];
            }
            throw e;
        }

        // --- Lint ---
        const linter = new Linter(RS, toplevel, code, this._builtins);
        toplevel.walk(linter);
        messages = linter.resolve(noqa);

        return messages.map(m => to_marker(m, markerSeverity));
    }
}


// ── analyzer.js ─────────────────────────────────────────────────────────

// analyzer.js — AST walker that builds a ScopeMap for a RapydScript source file.
//
// Usage:
//   import { SourceAnalyzer } from './analyzer.js';
//   const analyzer = new SourceAnalyzer(compiler);
//   const scopeMap = analyzer.analyze(sourceCode, { virtualFiles: {...} });


// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert AST token position {line (1-indexed), col (0-indexed)} → {line, column} (both 1-indexed). */
function pos_from_token(tok) {
    if (!tok) return { line: 1, column: 1 };
    return { line: tok.line, column: tok.col + 1 };
}

/**
 * Extract the first docstring value from a scope node, if present.
 * The parser populates node.docstrings for AST_Scope nodes.
 */
function extract_doc(node) {
    if (node.docstrings && node.docstrings.length > 0) {
        const ds = node.docstrings[0];
        return ds.value !== undefined ? ds.value : null;
    }
    return null;
}

/**
 * Collect parameter descriptors from an AST_Lambda node.
 * Handles regular args, *args (starargs), and **kwargs.
 */
function extract_params(lambda_node) {
    const params = [];
    const argnames = lambda_node.argnames;
    if (!argnames) return params;

    argnames.forEach(arg => {
        if (arg && arg.name) params.push({ name: arg.name, is_rest: false, is_kwargs: false });
    });
    if (argnames.starargs && argnames.starargs.name) {
        params.push({ name: argnames.starargs.name, is_rest: true,  is_kwargs: false });
    }
    if (argnames.kwargs && argnames.kwargs.name) {
        params.push({ name: argnames.kwargs.name,  is_rest: false, is_kwargs: true  });
    }
    return params;
}

// ---------------------------------------------------------------------------
// ScopeBuilder — internal AST visitor
// Mirrors the structure of tools/lint.js's Linter but builds a ScopeMap
// instead of recording lint errors.
// ---------------------------------------------------------------------------

class ScopeBuilder {
    constructor(RS, map) {
        this._RS          = RS;
        this._map         = map;
        this._scopes      = [];   // stack of ScopeFrame
        this.current_node = null;
    }

    _current_scope() {
        return this._scopes.length ? this._scopes[this._scopes.length - 1] : null;
    }

    _push_scope(kind, name, node) {
        const parent = this._current_scope();
        const depth  = parent ? parent.depth + 1 : 0;

        const start_tok = node.start;
        const end_tok   = node.end;

        const frame = new ScopeFrame({
            kind,
            name,
            range: {
                start: start_tok ? { line: start_tok.line, column: start_tok.col + 1 } : { line: 1, column: 1 },
                end:   end_tok   ? { line: end_tok.line,   column: end_tok.col   + 1 } : { line: 999999, column: 999999 },
            },
            parent,
            depth,
        });

        this._map.addFrame(frame);
        this._scopes.push(frame);
        return frame;
    }

    _pop_scope() {
        return this._scopes.pop();
    }

    _add_symbol(opts) {
        const scope = this._current_scope();
        if (!scope || !opts.name) return null;
        const sym = new SymbolInfo({
            name:           opts.name,
            kind:           opts.kind,
            defined_at:     opts.defined_at || { line: 1, column: 1 },
            scope_depth:    scope.depth,
            doc:            opts.doc            || null,
            params:         opts.params         || null,
            inferred_class: opts.inferred_class || null,
        });
        scope.addSymbol(sym);
        return sym;
    }

    // ---- The visitor function called by node.walk() ----------------------

    _visit(node, cont) {
        this.current_node = node;
        const RS          = this._RS;
        const prev_depth  = this._scopes.length;

        // ------------------------------------------------------------------
        // 1. Scope-creating nodes — push a frame BEFORE recursing.
        //    Order matters: more specific classes first (AST_Method < AST_Lambda < AST_Scope).
        // ------------------------------------------------------------------

        if (node instanceof RS.AST_Lambda) {
            // Covers AST_Function and AST_Method.
            const is_method = node instanceof RS.AST_Method;
            const name      = node.name ? node.name.name : null;

            // Add the function/method symbol to the PARENT scope first.
            if (name) {
                const parent = this._current_scope();
                if (parent) {
                    const sym = new SymbolInfo({
                        name,
                        kind:        is_method ? 'method' : 'function',
                        defined_at:  pos_from_token(node.start),
                        scope_depth: parent.depth,
                        doc:         extract_doc(node),
                        params:      extract_params(node),
                    });
                    parent.addSymbol(sym);
                }
            }

            // Push a new scope for the function body.
            this._push_scope(is_method ? 'function' : 'function', name, node);

        } else if (node instanceof RS.AST_Class) {
            const name = node.name ? node.name.name : null;

            // Add class symbol to the parent scope.
            if (name) {
                const parent = this._current_scope();
                if (parent) {
                    parent.addSymbol(new SymbolInfo({
                        name,
                        kind:        'class',
                        defined_at:  pos_from_token(node.start),
                        scope_depth: parent.depth,
                        doc:         extract_doc(node),
                        params:      null,
                    }));
                }
            }

            // Push class scope.
            this._push_scope('class', name, node);

        } else if (node instanceof RS.AST_ListComprehension) {
            // AST_ListComprehension extends AST_ForIn, NOT AST_Scope.
            // We give it its own scope so its loop variable doesn't leak.
            this._push_scope('comprehension', null, node);

            // The loop variable (node.init) is visited by the walk, but we
            // add it now so it lands in the comprehension frame.
            if (node.init instanceof RS.AST_SymbolRef) {
                this._add_symbol({
                    name:       node.init.name,
                    kind:       'variable',
                    defined_at: pos_from_token(node.init.start),
                });
                node.init.scope_builder_visited = true;
            }

        } else if (node instanceof RS.AST_Scope) {
            // AST_Toplevel and any other raw scope nodes.
            const kind = node instanceof RS.AST_Toplevel ? 'module' : 'block';
            this._push_scope(kind, null, node);
        }

        // ------------------------------------------------------------------
        // 2. Symbol-producing nodes (order doesn't matter for these).
        // ------------------------------------------------------------------

        if (node instanceof RS.AST_SymbolFunarg) {
            // A regular function parameter; starargs/kwargs are also SymbolFunarg.
            this._add_symbol({
                name:       node.name,
                kind:       'parameter',
                defined_at: pos_from_token(node.start),
            });

        } else if (node instanceof RS.AST_ImportedVar) {
            // `from X import name` or `from X import name as alias`
            const name = (node.alias && node.alias.name) ? node.alias.name : node.name;
            if (name) {
                this._add_symbol({
                    name,
                    kind:       'import',
                    defined_at: pos_from_token(node.start),
                });
            }

        } else if (node instanceof RS.AST_Import && !node.argnames) {
            // `import X` or `import X as Y` (no from-clause)
            const name = (node.alias && node.alias.name)
                ? node.alias.name
                : (node.key ? node.key.split('.')[0] : null);
            if (name) {
                this._add_symbol({
                    name,
                    kind:       'import',
                    defined_at: pos_from_token(node.start),
                });
            }

        } else if (node instanceof RS.AST_VarDef) {
            // `var` declarations emitted by the compiler; name can be SymbolVar or SymbolNonlocal.
            if (node.name && !(node.name instanceof RS.AST_SymbolNonlocal)) {
                const name = typeof node.name.name === 'string' ? node.name.name : null;
                if (name) {
                    this._add_symbol({
                        name,
                        kind:       'variable',
                        defined_at: pos_from_token(node.start),
                    });
                }
            }

        } else if (node instanceof RS.AST_Assign && node.operator === '=') {
            // Simple assignment: add left-hand symbol if new to this scope.
            if (node.left instanceof RS.AST_SymbolRef) {
                const name  = node.left.name;
                const scope = this._current_scope();
                if (scope && !scope.getSymbol(name)) {
                    // Detect `x = ClassName(...)` to record the inferred type.
                    let inferred_class = null;
                    if (node.right instanceof RS.AST_BaseCall &&
                        node.right.expression instanceof RS.AST_SymbolRef) {
                        inferred_class = node.right.expression.name;
                    }
                    this._add_symbol({
                        name,
                        kind:           'variable',
                        defined_at:     pos_from_token(node.left.start),
                        inferred_class,
                    });
                }
            }

        } else if (
            node instanceof RS.AST_ForIn &&
            !(node instanceof RS.AST_ListComprehension) &&
            node.init instanceof RS.AST_SymbolRef &&
            !node.init.scope_builder_visited
        ) {
            // Regular `for x in ...` loop variable.
            this._add_symbol({
                name:       node.init.name,
                kind:       'variable',
                defined_at: pos_from_token(node.init.start),
            });
            node.init.scope_builder_visited = true;

        } else if (node instanceof RS.AST_Except && node.argname) {
            // `except SomeError as e`
            this._add_symbol({
                name:       node.argname.name,
                kind:       'variable',
                defined_at: pos_from_token(node.argname.start),
            });

        } else if (node instanceof RS.AST_WithClause && node.alias) {
            // `with ctx as alias`
            this._add_symbol({
                name:       node.alias.name,
                kind:       'variable',
                defined_at: pos_from_token(node.alias.start),
            });
        }

        // ------------------------------------------------------------------
        // 3. Recurse into child nodes.
        // ------------------------------------------------------------------

        if (cont) cont();

        // ------------------------------------------------------------------
        // 4. Pop the scope we pushed (if any).
        // ------------------------------------------------------------------

        if (this._scopes.length > prev_depth) {
            this._pop_scope();
        }
    }
}

// ---------------------------------------------------------------------------
// SourceAnalyzer — public API
// ---------------------------------------------------------------------------

class SourceAnalyzer {
    /**
     * @param {object} compiler  - window.RapydScript (the compiled compiler bundle)
     */
    constructor(compiler) {
        this._RS = compiler;
    }

    /**
     * Parse `code` and walk the resulting AST to build a ScopeMap.
     * Returns an empty ScopeMap if parsing fails.
     *
     * @param {string} code
     * @param {object} [options]
     * @param {object} [options.virtualFiles]  - map of module-name → source
     * @returns {ScopeMap}
     */
    analyze(code, options) {
        options = options || {};
        const RS  = this._RS;
        const map = new ScopeMap();

        let toplevel;
        try {
            toplevel = RS.parse(code, {
                filename:    'editor.pyj',
                for_linting: true,
                ...(options.virtualFiles ? { virtual_files: options.virtualFiles } : {}),
            });
        } catch (_e) {
            // Syntax/import error — return the empty map; diagnostics.js handles errors.
            return map;
        }

        const builder = new ScopeBuilder(RS, map);
        toplevel.walk(builder);
        return map;
    }
}


// ── completions.js ──────────────────────────────────────────────────────

// completions.js — Completion item provider for the RapydScript language service.
//
// Usage:
//   import { CompletionEngine } from './completions.js';
//   const engine = new CompletionEngine(analyzer, { virtualFiles, builtinNames });
//   const items  = engine.getCompletions(scopeMap, position, linePrefix, monacoKind);


// ---------------------------------------------------------------------------
// Context detection
// ---------------------------------------------------------------------------

/**
 * Inspect the text before the cursor and classify what kind of completion
 * is appropriate.
 *
 * Returns one of:
 *   { type: 'dot',         objectName: string, prefix: string }
 *   { type: 'from_import', moduleName: string, prefix: string }
 *   { type: 'import',      prefix: string }
 *   { type: 'identifier',  prefix: string }
 *
 * @param {string} linePrefix  text from column 1 up to (but not including) the cursor
 * @returns {{ type: string, objectName?: string, moduleName?: string, prefix: string }}
 */
function detect_context(linePrefix) {
    // `obj.attr` — dot access
    const dot_match = linePrefix.match(/(\w+)\.([\w]*)$/);
    if (dot_match) {
        return { type: 'dot', objectName: dot_match[1], prefix: dot_match[2] };
    }

    // `from modname import partial`
    const from_match = linePrefix.match(/^\s*from\s+([\w.]+)\s+import\s+([\w]*)$/);
    if (from_match) {
        return { type: 'from_import', moduleName: from_match[1], prefix: from_match[2] };
    }

    // `import partial` (bare import at start of line)
    const import_match = linePrefix.match(/^\s*import\s+([\w.]*)$/);
    if (import_match) {
        return { type: 'import', prefix: import_match[1] };
    }

    // Default: identifier completion
    const ident_match = linePrefix.match(/(\w*)$/);
    return { type: 'identifier', prefix: ident_match ? ident_match[1] : '' };
}

// ---------------------------------------------------------------------------
// Monaco item helpers
// ---------------------------------------------------------------------------

/**
 * Build a Monaco IRange covering the word currently being typed.
 * @param {{lineNumber:number,column:number}} position  Monaco 1-indexed position
 * @param {string} prefix  the portion of the word already typed
 * @returns {{startLineNumber,startColumn,endLineNumber,endColumn}}
 */
function word_range(position, prefix) {
    return {
        startLineNumber: position.lineNumber,
        startColumn:     position.column - prefix.length,
        endLineNumber:   position.lineNumber,
        endColumn:       position.column,
    };
}

/**
 * Map a SymbolInfo kind to a Monaco CompletionItemKind value.
 * monacoKind is the Monaco.languages.CompletionItemKind enum object.
 * @param {string} kind
 * @param {object} monacoKind
 * @returns {number}
 */
function kind_to_monaco(kind, monacoKind) {
    switch (kind) {
        case 'function':  return monacoKind.Function;
        case 'method':    return monacoKind.Method;
        case 'class':     return monacoKind.Class;
        case 'parameter': return monacoKind.Variable;
        case 'import':    return monacoKind.Module;
        default:          return monacoKind.Variable;
    }
}

/**
 * Build a Monaco CompletionItem from a SymbolInfo.
 * @param {import('./scope.js').SymbolInfo} sym
 * @param {object} range   Monaco IRange
 * @param {object} monacoKind  Monaco CompletionItemKind enum
 * @param {string} sortPrefix  e.g. '0', '1', '2' for ranking
 * @returns {object}  Monaco CompletionItem
 */
function symbol_to_item(sym, range, monacoKind, sortPrefix) {
    let detail = sym.kind;
    if (sym.params) {
        const param_str = sym.params.map(p => {
            if (p.is_kwargs) return '**' + p.name;
            if (p.is_rest)   return '*'  + p.name;
            return p.name;
        }).join(', ');
        detail = '(' + param_str + ')';
    }
    return {
        label:            sym.name,
        kind:             kind_to_monaco(sym.kind, monacoKind),
        detail,
        documentation:    sym.doc || undefined,
        sortText:         sortPrefix + '_' + sym.name,
        insertText:       sym.name,
        range,
    };
}

/**
 * Build a simple completion item from a plain name string (e.g. a builtin).
 * @param {string} name
 * @param {object} range
 * @param {object} monacoKind
 * @returns {object}
 */
function name_to_item(name, range, monacoKind) {
    return {
        label:      name,
        kind:       monacoKind.Variable,
        sortText:   '2_' + name,
        insertText: name,
        range,
    };
}

// ---------------------------------------------------------------------------
// CompletionEngine
// ---------------------------------------------------------------------------

class CompletionEngine {
    /**
     * @param {import('./analyzer.js').SourceAnalyzer} analyzer
     * @param {object} opts
     * @param {object} [opts.virtualFiles]   module-name → source
     * @param {string[]} [opts.builtinNames] names always available (BASE_BUILTINS + extras)
     */
    constructor(analyzer, opts) {
        this._analyzer     = analyzer;
        this._virtualFiles = opts.virtualFiles || {};
        this._builtinNames = opts.builtinNames || [];
    }

    /**
     * Update the virtual files available to import analysis.
     * @param {object} virtualFiles
     */
    setVirtualFiles(virtualFiles) {
        this._virtualFiles = virtualFiles;
    }

    /**
     * Produce Monaco completion items for the given position.
     *
     * @param {import('./scope.js').ScopeMap|null} scopeMap
     * @param {{lineNumber:number,column:number}} position  1-indexed Monaco position
     * @param {string} linePrefix  text on the current line up to the cursor
     * @param {object} monacoKind  Monaco.languages.CompletionItemKind enum
     * @returns {{ suggestions: object[] }}  Monaco CompletionList
     */
    getCompletions(scopeMap, position, linePrefix, monacoKind) {
        const ctx = detect_context(linePrefix);

        if (ctx.type === 'dot') {
            return { suggestions: this._dot_completions(scopeMap, position, ctx, monacoKind) };
        }
        if (ctx.type === 'from_import') {
            return { suggestions: this._from_import_completions(position, ctx, monacoKind) };
        }
        if (ctx.type === 'import') {
            return { suggestions: this._module_name_completions(position, ctx, monacoKind) };
        }
        // Default: identifier completions from scope + builtins
        return { suggestions: this._scope_completions(scopeMap, position, ctx, monacoKind) };
    }

    // ---- Identifier completions (scope + builtins) -------------------------

    _scope_completions(scopeMap, position, ctx, monacoKind) {
        const range   = word_range(position, ctx.prefix);
        const items   = [];
        const seen    = new Set();

        if (scopeMap) {
            const symbols = scopeMap.getSymbolsAtPosition(position.lineNumber, position.column);
            for (const sym of symbols) {
                if (!ctx.prefix || sym.name.startsWith(ctx.prefix)) {
                    if (!seen.has(sym.name)) {
                        seen.add(sym.name);
                        const sort = sym.scope_depth > 0 ? '0' : '1';
                        items.push(symbol_to_item(sym, range, monacoKind, sort));
                    }
                }
            }
        }

        // Builtins (lowest priority)
        for (const name of this._builtinNames) {
            if (!seen.has(name) && (!ctx.prefix || name.startsWith(ctx.prefix))) {
                seen.add(name);
                items.push(name_to_item(name, range, monacoKind));
            }
        }

        return items;
    }

    // ---- Dot completions ---------------------------------------------------

    _dot_completions(scopeMap, position, ctx, monacoKind) {
        const range = word_range(position, ctx.prefix);
        const items = [];
        const seen  = new Set();

        if (!scopeMap) return items;

        // Resolve the object: direct class name, or instance with inferred_class.
        const obj_sym = scopeMap.getSymbol(
            ctx.objectName,
            position.lineNumber,
            position.column
        );

        let class_name = null;
        if (obj_sym) {
            if (obj_sym.kind === 'class') {
                class_name = obj_sym.name;
            } else if (obj_sym.inferred_class) {
                class_name = obj_sym.inferred_class;
            }
        }

        if (class_name) {
            // Find the class frame in the ScopeMap and emit its symbols.
            for (const frame of scopeMap.frames) {
                if (frame.kind === 'class' && frame.name === class_name) {
                    for (const [name, sym] of frame.symbols) {
                        if (!ctx.prefix || name.startsWith(ctx.prefix)) {
                            if (!seen.has(name)) {
                                seen.add(name);
                                items.push(symbol_to_item(sym, range, monacoKind, '0'));
                            }
                        }
                    }
                }
            }
        }

        return items;
    }

    // ---- from X import completions -----------------------------------------

    _from_import_completions(position, ctx, monacoKind) {
        const range = word_range(position, ctx.prefix);
        const items = [];

        const src = this._virtualFiles[ctx.moduleName];
        if (!src) return items;

        let scopeMap;
        try {
            scopeMap = this._analyzer.analyze(src, {});
        } catch (_e) {
            return items;
        }

        // Return all module-level symbols
        const module_frame = scopeMap.frames.find(f => f.kind === 'module');
        if (!module_frame) return items;

        for (const [name, sym] of module_frame.symbols) {
            if (!ctx.prefix || name.startsWith(ctx.prefix)) {
                items.push(symbol_to_item(sym, range, monacoKind, '0'));
            }
        }
        return items;
    }

    // ---- import module name completions ------------------------------------

    _module_name_completions(position, ctx, monacoKind) {
        const range = word_range(position, ctx.prefix);
        const items = [];
        const seen  = new Set();

        for (const modname of Object.keys(this._virtualFiles)) {
            if (!ctx.prefix || modname.startsWith(ctx.prefix)) {
                if (!seen.has(modname)) {
                    seen.add(modname);
                    items.push({
                        label:      modname,
                        kind:       monacoKind.Module,
                        sortText:   '0_' + modname,
                        insertText: modname,
                        range,
                    });
                }
            }
        }
        return items;
    }
}


// ── index.js ────────────────────────────────────────────────────────────

// index.js — RapydScript Monaco Language Service
// Public API: registerRapydScript(monaco, options) → service
//
// Usage:
//   import { registerRapydScript } from './monaco-language-service/index.js';
//
//   const service = registerRapydScript(monaco, {
//     compiler:     window.RapydScript,   // compiled rapydscript bundle
//     virtualFiles: { 'mymod': 'def f(): pass' },  // optional
//     dtsFiles:     [{ name: 'dom', content: '...' }],  // optional (Phase 6)
//     parseDelay:   300,  // ms debounce (default: 300)
//   });
//
//   service.setVirtualFiles({ 'mymod': newSource });
//   service.addDts('name', dtsText);   // Phase 6 stub for now
//   service.dispose();                 // remove all Monaco providers


const LANGUAGE_ID = 'rapydscript';

// ---------------------------------------------------------------------------
// Per-model state
// ---------------------------------------------------------------------------

class ModelState {
    constructor(model, service) {
        this._model    = model;
        this._service  = service;
        this._timer    = null;
        this._scopeMap = null;  // most recent ScopeMap for this model

        // Run immediately on first attach
        this._schedule(0);

        // Re-run on every edit
        this._subscription = model.onDidChangeContent(() => {
            this._schedule(service._parseDelay);
        });
    }

    _schedule(delay) {
        clearTimeout(this._timer);
        this._timer = setTimeout(() => this._run(), delay);
    }

    _run() {
        const service = this._service;
        const code    = this._model.getValue();
        const opts    = { virtualFiles: service._virtualFiles };

        // Diagnostics (syntax errors + lint markers)
        const markers = service._diagnostics.check(code, {
            ...opts,
            markerSeverity: service._monaco.MarkerSeverity,
        });
        service._monaco.editor.setModelMarkers(this._model, LANGUAGE_ID, markers);

        // Scope analysis (feeds Phase 3 completions and Phase 5 hover)
        this._scopeMap = service._analyzer.analyze(code, opts);
    }

    dispose() {
        clearTimeout(this._timer);
        this._subscription.dispose();
        // Clear markers when detaching
        this._service._monaco.editor.setModelMarkers(this._model, LANGUAGE_ID, []);
    }
}

// ---------------------------------------------------------------------------
// RapydScriptLanguageService
// ---------------------------------------------------------------------------

class RapydScriptLanguageService {
    constructor(monaco, options) {
        this._monaco       = monaco;
        this._parseDelay   = options.parseDelay !== undefined ? options.parseDelay : 300;
        this._virtualFiles = Object.assign({}, options.virtualFiles || {});
        this._disposables  = [];
        this._modelStates  = new Map();  // model → ModelState

        // Build compiler reference — accept either the raw RapydScript global
        // or a web_repl instance (we only need the parse-level API).
        const compiler = options.compiler;
        if (!compiler) throw new Error('registerRapydScript: options.compiler is required');

        this._diagnostics = new Diagnostics(compiler, options.extraBuiltins);
        this._analyzer    = new SourceAnalyzer(compiler);

        // Merge BASE_BUILTINS with any extra globals for completions
        const builtin_names = BASE_BUILTINS.concat(
            options.extraBuiltins ? Object.keys(options.extraBuiltins) : []
        );
        this._completions = new CompletionEngine(this._analyzer, {
            virtualFiles: this._virtualFiles,
            builtinNames: builtin_names,
        });

        // Register language id if not already registered
        const existing = monaco.languages.getLanguages().find(l => l.id === LANGUAGE_ID);
        if (!existing) monaco.languages.register({ id: LANGUAGE_ID });

        // Attach to all currently open rapydscript models
        monaco.editor.getModels().forEach(model => this._maybeAttach(model));

        // Attach to future models
        this._disposables.push(
            monaco.editor.onDidCreateModel(model => this._maybeAttach(model))
        );

        // Detach when a model is disposed
        this._disposables.push(
            monaco.editor.onWillDisposeModel(model => this._detach(model))
        );

        // Register completion provider
        const self = this;
        this._disposables.push(
            monaco.languages.registerCompletionItemProvider(LANGUAGE_ID, {
                triggerCharacters: ['.'],
                provideCompletionItems(model, position) {
                    if (model.getLanguageId() !== LANGUAGE_ID) return { suggestions: [] };
                    const state = self._modelStates.get(model);
                    const scopeMap = state ? state._scopeMap : null;
                    const line_content = model.getLineContent(position.lineNumber);
                    const line_prefix  = line_content.substring(0, position.column - 1);
                    return self._completions.getCompletions(
                        scopeMap,
                        position,
                        line_prefix,
                        monaco.languages.CompletionItemKind
                    );
                },
            })
        );
    }

    // ---- internal ----------------------------------------------------------

    _maybeAttach(model) {
        if (model.getLanguageId() !== LANGUAGE_ID) return;
        if (this._modelStates.has(model)) return;
        this._modelStates.set(model, new ModelState(model, this));
    }

    _detach(model) {
        const state = this._modelStates.get(model);
        if (!state) return;
        state.dispose();
        this._modelStates.delete(model);
    }

    // ---- public API --------------------------------------------------------

    /**
     * Replace / merge virtual files available to the import resolver.
     * Triggers an immediate re-check of all open models.
     * @param {Object.<string,string>} files
     */
    setVirtualFiles(files) {
        Object.assign(this._virtualFiles, files);
        this._completions.setVirtualFiles(this._virtualFiles);
        this._modelStates.forEach(state => state._schedule(0));
    }

    /**
     * Remove a virtual file by name.
     * @param {string} name
     */
    removeVirtualFile(name) {
        delete this._virtualFiles[name];
        this._completions.setVirtualFiles(this._virtualFiles);
        this._modelStates.forEach(state => state._schedule(0));
    }

    /**
     * Add additional global symbol names (e.g. from d.ts) so they are not
     * flagged as undefined.  Phase 6 will call this automatically.
     * @param {string[]} names
     */
    addGlobals(names) {
        this._diagnostics.addGlobals(names);
        this._modelStates.forEach(state => state._schedule(0));
    }

    /**
     * Return the most recently built ScopeMap for a given Monaco model.
     * Returns null if the model is not attached or has not been analysed yet.
     * Used by Phase 3 (completions) and Phase 5 (hover).
     * @param {object} model - Monaco ITextModel
     * @returns {import('./scope.js').ScopeMap|null}
     */
    getScopeMap(model) {
        const state = this._modelStates.get(model);
        return state ? state._scopeMap : null;
    }

    /**
     * Stub for Phase 6 (DtsRegistry).  Calling it is safe but has no effect yet.
     * @param {string} _name
     * @param {string} _dtsText
     */
    // eslint-disable-next-line no-unused-vars
    addDts(_name, _dtsText) {
        // Phase 6 will implement this.
        console.warn('RapydScript language service: addDts() not yet implemented (Phase 6).');
    }

    /**
     * Remove all Monaco providers and event listeners registered by this service.
     */
    dispose() {
        this._modelStates.forEach(state => state.dispose());
        this._modelStates.clear();
        this._disposables.forEach(d => d.dispose());
        this._disposables = [];
    }
}

// ---------------------------------------------------------------------------
// Exported factory
// ---------------------------------------------------------------------------

/**
 * Register the RapydScript language service with a Monaco instance.
 *
 * @param {object} monaco   - the Monaco global (window.monaco or require('monaco-editor'))
 * @param {object} options
 * @param {object} options.compiler          - window.RapydScript compiled bundle (required)
 * @param {object} [options.virtualFiles]    - map of module-name → source
 * @param {Array}  [options.dtsFiles]        - [{name, content}] d.ts files (Phase 6)
 * @param {number} [options.parseDelay=300]  - debounce ms
 * @param {object} [options.extraBuiltins]   - extra {name: true} globals to suppress undef warnings
 * @returns {RapydScriptLanguageService}
 */
function registerRapydScript(monaco, options) {
    return new RapydScriptLanguageService(monaco, options || {});
}

export { registerRapydScript };
